prometheus:
  prometheusSpec:
    retention: 7d
    scrapeInterval: 15s
    additionalScrapeConfigs:
      - job_name: ai-platform
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - ai-devsecops
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: "true"
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__

grafana:
  enabled: true
  adminPassword: admin
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: ai-platform
          orgId: 1
          folder: AI Platform
          type: file
          options:
            path: /var/lib/grafana/dashboards/ai-platform
  dashboardsConfigMaps:
    ai-platform: "grafana-dashboards"
