apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "spring-boot-app.fullname" . }}
spec:
  ingressClassName: nginx

  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "spring-boot-app.fullname" . }}-service
                port:
                  number: {{ .Values.service.port }}
