apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-worker
  namespace: ai-devsecops
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ai-worker
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
