apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-platform-config
  namespace: ai-devsecops
  labels:
    app.kubernetes.io/part-of: ai-native-devsecops-platform
    app.kubernetes.io/managed-by: kustomize
data:
  AI_PROVIDER: "mock"
  REDIS_CONNECTION_STRING: "redis:6379"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
