apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-platform-sa
  namespace: ai-devsecops
  labels:
    app.kubernetes.io/part-of: ai-native-devsecops-platform
automountServiceAccountToken: false
