apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-spring-boot-image
spec:
  validationFailureAction: Enforce
  background: false

  rules:
    - name: verify-spring-boot-cosign
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - project18

      verifyImages:
        - imageReferences:
            - "tushar31/spring-boot-app:*"

          attestors:
            - entries:
                - keys:
                    secret:
                      name: cosign-public-key
                      namespace: kyverno

          attestations:
            - type: "https://in-toto.io/attestation/v1"

              attestors:
                - entries:
                    - keys:
                        secret:
                          name: cosign-public-key
                          namespace: kyverno

              conditions:
                - all:
                    - key: "{{ builder.id }}"
                      operator: Equals
                      value: "http://172.172.234.187:8080/job/DevOps-Project-18"

                    - key: "{{ predicate.repository }}"
                      operator: Equals
                      value: "https://github.com/RawatTushar/DevOps-Projects.git"

                    - key: "{{ predicate.buildType }}"
                      operator: Equals
                      value: "https://jenkins.io/build"

                    - key: "{{ predicate.imageDigest }}"
                      operator: Equals
                      value: "{{ subject[0].digest.sha256 }}"