apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-devsecops

resources:
  - ../../base

patches:
  - path: api-deployment-patch.yaml
  - path: worker-deployment-patch.yaml

configMapGenerator:
  - name: ai-platform-config
    behavior: merge
    literals:
      - AI_PROVIDER=mock
      - ASPNETCORE_ENVIRONMENT=Development
    options:
      disableNameSuffixHash: true

secretGenerator:
  - name: postgres-secret
    literals:
      - password=aiops-dev-password
    options:
      disableNameSuffixHash: true
  - name: ai-platform-secrets
    literals:
      - POSTGRES_CONNECTION_STRING=Host=postgres;Database=aiops;Username=aiops;Password=aiops-dev-password
    options:
      disableNameSuffixHash: true

images:
  - name: ghcr.io/GITHUB_REPOSITORY/ai-api
    newTag: dev
  - name: ghcr.io/GITHUB_REPOSITORY/ai-worker
    newTag: dev
